spring.application.name=GymTrackerAPI
server.forward-headers-strategy=framework
spring.profiles.active=${ACTIVE_PROFILE:prod}

app.base-url=${NGINX_BASE_URL:http://localhost:8080}
app.email-address=${EMAIL_ADDRESS}

app.security.jwt.secret-key=${JWT.SECRET_KEY}

app.security.jwt.access-token.expiration=${ACCESS_TOKEN.EXPIRATION}
app.security.jwt.refresh-token.expiration=${REFRESH_TOKEN.EXPIRATION}

spring.mail.host=localhost
