spring.application.name=GymTrackerAPI

app.cors.allowed-origin = ${CORS_ORIGIN:http://localhost:3000}
app.security.jwt.secret-key=${JWT.SECRET_KEY}

app.security.jwt.access-token.expiration=${ACCESS_TOKEN.EXPIRATION}
app.security.jwt.refresh-token.expiration=${ACCESS_TOKEN.SECRET_KEY}
