spring.application.name=GymTrackerAPI
spring.profiles.active=${ACTIVE_PROFILE:prod}

app.base-url=${BASE_URL:http://localhost:8080}
app.email-address=${EMAIL_ADDRESS}

app.cors.allowed-origin = ${CORS_ORIGIN:http://localhost:3000}
app.security.jwt.secret-key=${JWT.SECRET_KEY}

app.security.jwt.access-token.expiration=${ACCESS_TOKEN.EXPIRATION}
app.security.jwt.refresh-token.expiration=${REFRESH_TOKEN.EXPIRATION}

spring.mail.host=localhost
